language: python

python: 3.5
sudo: false

env:
  - TRAVIS_NODE_VERSION="6"

services:
    - mongodb
    - elasticsearch
    - redis-server

addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.npm

before_install:
    - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
    - node --version
    - npm install -g npm@latest
    - npm config set loglevel warn

install:
    - npm install --python=python2.7
    - cd server && pip install -r requirements.txt && cd ..
    - gem install coveralls-lcov
before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
script:
    - make test
after_success:
    - coveralls-lcov -v -n coverage/lcov.info > coverage.json
    - coveralls --merge=coverage.json